name: build
# description:
# - Runs Gradle build compiling source code and executing tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Create release' }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.BUILD_POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Postgres Database and Service Account
        run: |
          psql -c "CREATE USER ${POSTGRES_DB_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_DB_PASSWORD}';" ${POSTGRES_URI}
          psql -f migrations/create_database.sql ${POSTGRES_URI}
        env:
          POSTGRES_URI: ${{ secrets.BUILD_POSTGRES_URI }}
          POSTGRES_DB_USER: ${{ secrets.BUILD_POSTGRES_DB_USER }}
          POSTGRES_DB_PASSWORD: ${{ secrets.BUILD_POSTGRES_DB_PASSWORD }}

      - name: Database Migration
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: flywayMigrate
          gradle-version: wrapper
        env:
          FLYWAY_URL: ${{ secrets.BUILD_POSTGRES_DB_URI }}
          FLYWAY_USER: ${{ secrets.BUILD_POSTGRES_DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.BUILD_POSTGRES_DB_PASSWORD }}

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          gradle-version: wrapper
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.BUILD_POSTGRES_DB_URI }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.BUILD_POSTGRES_DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.BUILD_POSTGRES_DB_PASSWORD }}

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.0

      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: FOSSA
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
